//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicalServerApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    


    public partial class TropicalServerEntities1 : DbContext
    {
        public TropicalServerEntities1()
            : base("name=TropicalServerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Models.tblCustomer> tblCustomers { get; set; }
        public DbSet<Models.tblOrder> tblOrders { get; set; }
    }
}
